### ISSUE TITLE
Buff translation issues

### ISSUE THREAD

**Issue by bluelanturn** [BluuArc/bf-mt#5]
When filterting proc buffs. Buffs from 24 onwards are all just listed as untranslated buffs

**Comment by BluuArc** [comment]
This is addressed in the upcoming squad update, targeted for June 2019

![image](https://user-images.githubusercontent.com/16447522/58373297-854aca00-7ef1-11e9-8b36-4aa481e99ddd.png)

**Comment by bluelanturn** [comment]
Thanks
