### ISSUE TITLE
Spark Simulator Squad Error "Map" Undefined

### ISSUE THREAD

**Issue by bluelanturn** [BluuArc/bf-mt#6]
After copying layout of the spark sim It resulted in the following error
![image](https://user-images.githubusercontent.com/51024827/58442490-135fc400-812f-11e9-94e6-fe0ee476de61.png)

**Comment by BluuArc** [comment]
Can you give the squad code here? You can get it by clicking "Share" then going to the "Code" tab. You should see something like this

![image](https://user-images.githubusercontent.com/16447522/58442715-a9a1d480-80b2-11e9-8fa4-c167f88dec11.png)


Also can you give me a screen shot of the simulator options you ran?

**Comment by bluelanturn** [comment]
820568~0~-~-~L~1~sbb~-,820658~1~-~-~-~3~sbb~-,X~2~-~-~F~4~atk~-,820558~3~-~-~-~5~sbb~-,820628~4~-~-~-~2~sbb~-,20997~5~-~-~-~6~sbb~-

**Comment by BluuArc** [comment]
I [pushed a fix](https://github.com/BluuArc/bf-mt/commit/e8355043bf2483786c3e687648d755ff14a131c4) that should have fixed it. Can you confirm that it's fixed on your end?

**Comment by bluelanturn** [comment]
Its fixed 👍
